import type { Area, BlogPost, Developer, Project, Property, TeamMember } from "./types";

const IMG = {
  apartment: ["Marina Gate Tower", "Downtown View", "Cityscape balcony"],
  villa: ["Garden villa estate", "Private pool villa", "Modern facade"],
  townhouse: ["Townhouse row", "Community park view"],
  penthouse: ["Sky penthouse terrace", "Panoramic skyline"],
  office: ["Business bay tower", "Corporate lobby"],
  retail: ["Retail plaza front", "Street level store"],
};

const thumb = (key: keyof typeof IMG, i = 0) => IMG[key][i % IMG[key].length];
const gallery = (key: keyof typeof IMG) => IMG[key];

export const PROPERTIES: Property[] = [
  {
    id: 101,
    slug: "marina-gate-2-bedroom-apartment-101",
    title: "Marina Gate II — 2 Bedroom Apartment",
    transaction: ["buy", "rent"],
    type: "apartment",
    area: "Dubai Marina",
    price: 2650000,
    pricePerYear: 115000,
    beds: 2,
    baths: 3,
    sqm: 118,
    thumb: thumb("apartment", 0),
    gallery: gallery("apartment"),
    coordinates: { lat: 25.0811, lng: 55.1405 },
    description:
      "Bright 2 bedroom apartment on a high floor at Marina Gate II with unobstructed marina views, floor-to-ceiling windows and access to resort-grade amenities including pools, gyms and a private cinema.",
    amenities: ["Swimming pool", "Gymnasium", "Concierge", "Covered parking", "Balcony", "24/7 Security"],
    maplink: "Dubai Marina, Dubai",
    dateAdded: "2026-07-18",
  },
  {
    id: 102,
    slug: "palm-jumeirah-signature-villa-102",
    title: "Signature Villa — Palm Jumeirah",
    transaction: ["buy"],
    type: "villa",
    area: "Palm Jumeirah",
    price: 48000000,
    beds: 6,
    baths: 8,
    sqm: 940,
    thumb: thumb("villa", 0),
    gallery: gallery("villa"),
    coordinates: { lat: 25.1124, lng: 55.1399 },
    description:
      "Bespoke six bedroom signature villa on the Palm Jumeirah frond with private beach access, infinity pool, landscaped gardens and panoramic views of the Dubai skyline.",
    amenities: ["Private beach", "Infinity pool", "Maid's room", "Lift", "Home cinema", "Landscaped garden"],
    maplink: "Palm Jumeirah, Dubai",
    dateAdded: "2026-07-10",
  },
  {
    id: 103,
    slug: "downtown-burj-view-townhouse-103",
    title: "Burj View Townhouse — Downtown",
    transaction: ["buy", "rent"],
    type: "townhouse",
    area: "Downtown Dubai",
    price: 8900000,
    pricePerYear: 220000,
    beds: 4,
    baths: 5,
    sqm: 310,
    thumb: thumb("townhouse", 0),
    gallery: gallery("townhouse"),
    coordinates: { lat: 25.1956, lng: 55.2742 },
    description:
      "Four bedroom townhouse steps from the Dubai Mall and Burj Khalifa, part of a low-rise community with private courtyard, rooftop terrace and direct access to landscaped podium gardens.",
    amenities: ["Rooftop terrace", "Courtyard", "Smart home", "Storage room", "Parking", "Podium gardens"],
    maplink: "Downtown Dubai, Dubai",
    dateAdded: "2026-06-28",
  },
  {
    id: 104,
    slug: "business-bay-office-suite-104",
    title: "Executive Office Suite — Business Bay",
    transaction: ["buy", "rent"],
    type: "office",
    area: "Business Bay",
    price: 1250000,
    pricePerYear: 62000,
    beds: 0,
    baths: 2,
    sqm: 85,
    thumb: thumb("office", 0),
    gallery: gallery("office"),
    coordinates: { lat: 25.185, lng: 55.279 },
    description:
      "Fitted executive office suite on a high floor of a Business Bay commercial tower with direct skyline views, dedicated parking, and premium lobby and conference facilities.",
    amenities: ["Fitted office", "Conference room", "Dedicated parking", "24/7 access", "Visitor lounge", "High speed lifts"],
    maplink: "Business Bay, Dubai",
    dateAdded: "2026-06-15",
  },
  {
    id: 105,
    slug: "dubai-hills-estate-villa-105",
    title: "Modern Villa — Dubai Hills Estate",
    transaction: ["buy"],
    type: "villa",
    area: "Dubai Hills Estate",
    price: 13500000,
    beds: 5,
    baths: 6,
    sqm: 480,
    thumb: thumb("villa", 1),
    gallery: gallery("villa"),
    coordinates: { lat: 25.057, lng: 55.16 },
    description:
      "Contemporary five bedroom villa backing onto the golf course at Dubai Hills Estate, featuring double-height living spaces, outdoor dining terrace and an expansive landscaped plot.",
    amenities: ["Golf course views", "Garden", "Maid's room", "Jacuzzi", "Smart home", "Double parking"],
    maplink: "Dubai Hills Estate, Dubai",
    dateAdded: "2026-05-30",
  },
  {
    id: 106,
    slug: "jlt-penthouse-full-skyline-106",
    title: "Skyline Penthouse — JLT",
    transaction: ["buy", "rent"],
    type: "penthouse",
    area: "Jumeirah Lakes Towers",
    price: 5600000,
    pricePerYear: 240000,
    beds: 3,
    baths: 4,
    sqm: 215,
    thumb: thumb("penthouse", 0),
    gallery: gallery("penthouse"),
    coordinates: { lat: 25.065, lng: 55.1403 },
    description:
      "Full-floor skyline penthouse at Jumeirah Lakes Towers with double-height ceilings, private elevator access, wraparound balcony and 360-degree views of the lake district and the Marina skyline.",
    amenities: ["Private lift", "Wraparound balcony", "Double height ceiling", "Valet", "Chef's kitchen", "Gym"],
    maplink: "Jumeirah Lakes Towers, Dubai",
    dateAdded: "2026-05-12",
  },
  {
    id: 107,
    slug: "city-walk-apartment-107",
    title: "City Walk — 1 Bedroom Apartment",
    transaction: ["rent"],
    type: "apartment",
    area: "City Walk",
    price: 145000,
    pricePerYear: 145000,
    beds: 1,
    baths: 2,
    sqm: 72,
    thumb: thumb("apartment", 1),
    gallery: gallery("apartment"),
    coordinates: { lat: 25.1882, lng: 55.2564 },
    description:
      "Stylish one bedroom apartment at City Walk, fully finished to a boutique standard with hotel-grade service, residents' lounge, and direct access to retail and dining streets.",
    amenities: ["Fully furnished", "Residents lounge", "Housekeeping", "Pool", "Gym", "Smart locks"],
    maplink: "City Walk, Dubai",
    dateAdded: "2026-04-22",
  },
  {
    id: 108,
    slug: "al-barsha-south-townhouse-108",
    title: "Al Barsha South Townhouse",
    transaction: ["buy", "rent"],
    type: "townhouse",
    area: "Al Barsha South",
    price: 2450000,
    pricePerYear: 98000,
    beds: 3,
    baths: 4,
    sqm: 210,
    thumb: thumb("townhouse", 1),
    gallery: gallery("townhouse"),
    coordinates: { lat: 25.031, lng: 55.221 },
    description:
      "Three bedroom townhouse in a family-centric Al Barsha South community with parks, a private garden, covered parking and proximity to the Expo City and Al Maktoum International Airport.",
    amenities: ["Private garden", "Community parks", "Kids pool", "Covered parking", "BBQ area", "Nearby metro"],
    maplink: "Al Barsha South, Dubai",
    dateAdded: "2026-04-05",
  },
];

export const PROJECTS: Project[] = [
  {
    id: 201,
    slug: "marina-vista-towers-201",
    name: "Marina Vista Towers",
    developer: "Emaar Properties",
    type: ["apartment", "penthouse"],
    status: "under-construction",
    handover: "Q4 2027",
    minPrice: 1850000,
    fromSqm: 92,
    beds: "1–4 BR",
    area: "Dubai Marina",
    thumb: "Marina Vista Towers render",
    gallery: ["Marina Vista lobby", "Marina Vista podium", "Marina Vista sky deck"],
    maplink: "Dubai Marina, Dubai",
    description:
      "Twin residential towers along the marina waterfront with resort-grade podium, sky lounges, and unobstructed marina and ocean views.",
    plans: ["1 BR · 92 sqm", "2 BR · 138 sqm", "3 BR · 186 sqm", "Penthouse · 320 sqm"],
    paymentPlan: [
      { title: "Down payment", value: "10%" },
      { title: "During construction", value: "50%" },
      { title: "On handover", value: "40%" },
    ],
    amenities: ["Beach access", "Sky pools", "Paddle courts", "Kids club", "Residents lounge", "Smart home"],
  },
  {
    id: 202,
    slug: "palm-frond-signature-homes-202",
    name: "Palm Frond Signature Homes",
    developer: "Nakheel",
    type: ["villa"],
    status: "launching",
    handover: "Q2 2028",
    minPrice: 24000000,
    fromSqm: 780,
    beds: "5–7 BR",
    area: "Palm Jumeirah",
    thumb: "Palm Frond Signature Homes",
    gallery: ["Palm beach frontage", "Palm home theatre", "Palm infinity pool"],
    maplink: "Palm Jumeirah, Dubai",
    description:
      "A limited collection of signature villas on the Palm Jumeirah fronds with private beach frontage, curated architecture and bespoke fit-out options.",
    plans: ["5 BR · 780 sqm", "6 BR · 910 sqm", "7 BR · 1100 sqm"],
    paymentPlan: [
      { title: "Down payment", value: "20%" },
      { title: "Milestone 1", value: "30%" },
      { title: "Milestone 2", value: "30%" },
      { title: "On handover", value: "20%" },
    ],
    amenities: ["Private beach", "Private pool", "Marina berth option", "Home automation", "Landscaped gardens"],
  },
  {
    id: 203,
    slug: "creek-harbour-residences-203",
    name: "Creek Harbour Residences",
    developer: "Emaar Properties",
    type: ["apartment", "townhouse"],
    status: "ready",
    handover: "Ready to move",
    minPrice: 1650000,
    fromSqm: 88,
    beds: "1–3 BR",
    area: "Dubai Creek Harbour",
    thumb: "Creek Harbour Residences",
    gallery: ["Creek promenade", "Creek pool deck", "Creek marina views"],
    maplink: "Dubai Creek Harbour, Dubai",
    description:
      "Ready residences overlooking the Dubai Creek waterfront, a short walk from the Creek Marina, the island promenade and the future Creek Tower.",
    plans: ["1 BR · 88 sqm", "2 BR · 126 sqm", "3 BR · 164 sqm"],
    paymentPlan: [{ title: "Payments", value: "Flexible plans" }],
    amenities: ["Marina views", "Creek promenade", "Pools", "Parking", "Gym", "Concierge"],
  },
  {
    id: 204,
    slug: "jvc-garden-terraces-204",
    name: "JVC Garden Terraces",
    developer: "Nakheel",
    type: ["townhouse", "apartment"],
    status: "under-construction",
    handover: "Q1 2027",
    minPrice: 920000,
    fromSqm: 68,
    beds: "1–3 BR",
    area: "Jumeirah Village Circle",
    thumb: "JVC Garden Terraces",
    gallery: ["JVC central park", "JVC terraces", "JVC family pool"],
    maplink: "Jumeirah Village Circle, Dubai",
    description:
      "Family-orientated mid-rise community wrapped around a central park, with terrace gardens, community pools and neighbourhood retail at street level.",
    plans: ["1 BR · 68 sqm", "2 BR · 102 sqm", "3 BR Townhouse · 148 sqm"],
    paymentPlan: [
      { title: "Down payment", value: "10%" },
      { title: "On milestones", value: "60%" },
      { title: "On handover", value: "30%" },
    ],
    amenities: ["Central park", "Community pools", "Playgrounds", "Retail strip", "Cycling tracks"],
  },
  {
    id: 205,
    slug: "business-bay-core-205",
    name: "Business Bay Core",
    developer: "Damac Properties",
    type: ["office", "apartment"],
    status: "under-construction",
    handover: "Q3 2027",
    minPrice: 1100000,
    fromSqm: 75,
    beds: "1–2 BR",
    area: "Business Bay",
    thumb: "Business Bay Core tower",
    gallery: ["Core lobby", "Core sky lounge", "Core meeting rooms"],
    maplink: "Business Bay, Dubai",
    description:
      "A mixed-use tower in the heart of Business Bay with flexible office suites and serviced apartments above a podium of retail and dining.",
    plans: ["Office · 75 sqm", "1 BR · 84 sqm", "2 BR · 128 sqm"],
    paymentPlan: [
      { title: "Down payment", value: "15%" },
      { title: "During construction", value: "45%" },
      { title: "On handover", value: "40%" },
    ],
    amenities: ["Meeting rooms", "Sky lounge", "Gym", "Concierge", "Dedicated parking"],
  },
  {
    id: 206,
    slug: "al-barari-oasis-estate-206",
    name: "Al Barari Oasis Estate",
    developer: "Al Barari",
    type: ["villa"],
    status: "completed",
    handover: "Completed",
    minPrice: 18500000,
    fromSqm: 560,
    beds: "4–6 BR",
    area: "Al Barari",
    thumb: "Al Barari Oasis Estate",
    gallery: ["Al Barari lake villa", "Al Barari gardens", "Al Barari wellness"],
    maplink: "Al Barari, Dubai",
    description:
      "Completed lakefront villas set among 13 million plants, with private gardens, organic farm access and the resort's signature wellness and spa amenities.",
    plans: ["4 BR · 560 sqm", "5 BR · 720 sqm", "6 BR · 890 sqm"],
    paymentPlan: [{ title: "Purchase", value: "Direct sale" }],
    amenities: ["Lake views", "Private gardens", "Wellness centre", "Golf access", "Organic farm"],
  },
];

export const AREAS: Area[] = [
  {
    id: 1,
    slug: "dubai-marina",
    name: "Dubai Marina",
    region: "New Dubai",
    avgPriceApartment: 2050,
    avgPriceVilla: 2900,
    yield: 6.2,
    img: "Dubai Marina waterfront",
    description:
      "A 50-metre wide canal city home to the world's largest marina berth community, high-rise living, and a waterfront promenade lined with dining and yachts.",
    highlights: ["Marina Walk", "JBR Beach", "Marina Mall", "Metro + Tram"],
  },
  {
    id: 2,
    slug: "downtown-dubai",
    name: "Downtown Dubai",
    region: "Central Dubai",
    avgPriceApartment: 2400,
    avgPriceVilla: 0,
    yield: 5.9,
    img: "Downtown Dubai skyline",
    description:
      "The city centre around the Burj Khalifa and Dubai Mall — the most iconic skyline address with unmatched tourism footfall and premium dining.",
    highlights: ["Burj Khalifa", "Dubai Mall", "Dubai Fountain", "Souk Al Bahar"],
  },
  {
    id: 3,
    slug: "palm-jumeirah",
    name: "Palm Jumeirah",
    region: "New Dubai",
    avgPriceApartment: 2750,
    avgPriceVilla: 3800,
    yield: 4.8,
    img: "Palm Jumeirah fronds",
    description:
      "The world-famous man-made island of fronds and luxury villas, beachfront hotels and an exclusive lifestyle with private shorelines.",
    highlights: ["Private beaches", "Atlantis", "The Pointe", "Nakheel Mall"],
  },
  {
    id: 4,
    slug: "business-bay",
    name: "Business Bay",
    region: "Central Dubai",
    avgPriceApartment: 1750,
    avgPriceVilla: 0,
    yield: 6.8,
    img: "Business Bay canal",
    description:
      "The commercial and residential corridor on the Dubai Canal with high-rise apartments, offices and growing retail around a landscaped promenade.",
    highlights: ["Dubai Canal", "Bay Avenue", "Canal Promenade", "Sheikh Zayed Road"],
  },
  {
    id: 5,
    slug: "dubai-hills-estate",
    name: "Dubai Hills Estate",
    region: "New Dubai",
    avgPriceApartment: 1900,
    avgPriceVilla: 2650,
    yield: 5.4,
    img: "Dubai Hills golf estate",
    description:
      "A master-planned golf community centred on an 18-hole championship course with villas, townhouses, apartments, a mall and acres of parks.",
    highlights: ["Golf Club", "Dubai Hills Mall", "Parks & trails", "Ras Al Khor sanctuary"],
  },
  {
    id: 6,
    slug: "jumeirah-village-circle",
    name: "Jumeirah Village Circle",
    region: "New Dubai",
    avgPriceApartment: 1450,
    avgPriceVilla: 1850,
    yield: 7.1,
    img: "JVC community park",
    description:
      "An affordable family community with parks, schools and retail within a quiet, landscaped loop — one of Dubai's highest rental-yield districts.",
    highlights: ["District parks", "Schools", "Retail strips", "Ring road access"],
  },
];

export const BLOG: BlogPost[] = [
  {
    id: 301,
    slug: "dubai-property-market-outlook-2026",
    title: "Dubai Property Market Outlook 2026: What Buyers Should Know",
    category: "Market Insights",
    date: "2026-07-21",
    readTime: "6 min read",
    img: "Dubai skyline outlook",
    excerpt:
      "From supply pipelines to rental growth, here is a data-led view of where Dubai's property market is heading this year — and what it means for buyers and renters.",
    body: [
      "Dubai's residential market enters 2026 with a healthy balance of demand and delivery. Over 90,000 units are expected to be completed across the emirate, with the majority concentrated in Dubai South, JVC and Business Bay.",
      "Rental growth has normalised to a mid-single-digit pace after several years of double-digit gains, while sales values continue to firm in waterfront and golf-community addresses.",
      "For buyers, the payment plan market remains strong, with several developers extending plans beyond handover. For renters, the key is locking in longer terms to protect against annual increases.",
    ],
    related: ["buying-off-plan-in-dubai-guide", "best-neighbourhoods-for-families-2026"],
  },
  {
    id: 302,
    slug: "buying-off-plan-in-dubai-guide",
    title: "Buying Off-Plan in Dubai: A Complete Guide for 2026",
    category: "Guides",
    date: "2026-07-12",
    readTime: "8 min read",
    img: "Off-plan towers cranes",
    excerpt:
      "Escrow accounts, RERA, payment plans, handover terms — everything you need to know before buying a property off-plan in Dubai.",
    body: [
      "Off-plan purchases in Dubai are protected by the RERA escrow framework: every project's sales must be registered in a dedicated escrow account, which funds construction and protects buyers if a developer defaults.",
      "Payment plans typically run 10% down, with the remainder split across construction milestones. Many 2026 launches stretch to 40% on handover, and some extend beyond.",
      "Before committing, review the developer's track record, the project's Oqood registration, and the projected service charges. A reputable agent will walk you through all three.",
    ],
    related: ["dubai-property-market-outlook-2026", "top-5-areas-for-rental-yield-2026"],
  },
  {
    id: 303,
    slug: "best-neighbourhoods-for-families-2026",
    title: "Best Neighbourhoods for Families in Dubai in 2026",
    category: "Area Guides",
    date: "2026-06-28",
    readTime: "5 min read",
    img: "Family community park",
    excerpt:
      "Schools, parks, safety and commute times — the shortlist of Dubai districts that family buyers keep returning to this year.",
    body: [
      "Dubai Hills Estate tops the list for families who want golf-course views, on-community schooling and a 15-minute commute to the city centre.",
      "Jumeirah Village Circle and Al Barsha South offer better value per square foot while remaining close to new schools, hospitals and the Expo City district.",
      "For villa families on the coast, Palm Jumeirah and Emirates Hills remain the prestige addresses, with the trade-off of higher entry prices and service charges.",
    ],
    related: ["buying-off-plan-in-dubai-guide", "top-5-areas-for-rental-yield-2026"],
  },
  {
    id: 304,
    slug: "top-5-areas-for-rental-yield-2026",
    title: "Top 5 Areas for Rental Yield in Dubai Right Now",
    category: "Investor Guides",
    date: "2026-06-10",
    readTime: "5 min read",
    img: "Rental yield chart",
    excerpt:
      "Gross yields across the city, and the five districts where investors are currently seeing the strongest rental returns.",
    body: [
      "Jumeirah Village Circle leads the yield table at 7%+ gross, driven by affordable entry prices and consistently high tenant demand.",
      "Business Bay, Dubai South and International City follow closely, while premium waterfront addresses settle in the 4.5–6% band.",
      "Remember that net yield subtracts service charges, agency fees and occasional vacancy — factor all three into your cash-flow model.",
    ],
    related: ["dubai-property-market-outlook-2026", "buying-off-plan-in-dubai-guide"],
  },
];

export const TEAM: TeamMember[] = [
  {
    id: 401,
    slug: "amira-haddad",
    name: "Amira Haddad",
    role: "Senior Sales Director",
    phone: "+971 50 111 2233",
    email: "amira@provident.ae",
    languages: ["English", "Arabic", "French"],
    specialties: ["Waterfront", "Off-plan", "Investment"],
    type: "leadership",
    img: "Amira Haddad portrait",
    bio: "Leading Zoya Ventures Real Estate's sales floor with 14 years across Dubai's marina and palm markets.",
  },
  {
    id: 402,
    slug: "daniel-reyes",
    name: "Daniel Reyes",
    role: "Senior Property Consultant",
    phone: "+971 50 222 3344",
    email: "daniel@provident.ae",
    languages: ["English", "Spanish"],
    specialties: ["Villas", "Golf communities"],
    type: "agent",
    img: "Daniel Reyes portrait",
    bio: "Villa specialist with a decade in Dubai Hills, Emirates Hills and the Palm.",
  },
  {
    id: 403,
    slug: "priya-sharma",
    name: "Priya Sharma",
    role: "Head of Investor Relations",
    phone: "+971 50 333 4455",
    email: "priya@provident.ae",
    languages: ["English", "Hindi", "Punjabi"],
    specialties: ["Investment", "Portfolio strategy"],
    type: "advisory",
    img: "Priya Sharma portrait",
    bio: "Guides high-net-worth and first-time investors through portfolio structuring and exit planning.",
  },
  {
    id: 404,
    slug: "omar-al-farsi",
    name: "Omar Al Farsi",
    role: "Senior Sales Executive",
    phone: "+971 50 444 5566",
    email: "omar@provident.ae",
    languages: ["English", "Arabic"],
    specialties: ["Downtown", "Commercial"],
    type: "agent",
    img: "Omar Al Farsi portrait",
    bio: "Downtown and commercial specialist, from Burj views to Business Bay suites.",
  },
  {
    id: 405,
    slug: "elena-kova",
    name: "Elena Kova",
    role: "Marketing & Partnerships Manager",
    phone: "+971 50 555 6677",
    email: "elena@provident.ae",
    languages: ["English", "Russian", "German"],
    specialties: ["Roadshows", "Overseas buyers"],
    type: "advisory",
    img: "Elena Kova portrait",
    bio: "Runs Zoya Ventures Real Estate's roadshow calendar and partnerships across Europe and Asia.",
  },
  {
    id: 406,
    slug: "james-oconnor",
    name: "James O'Connor",
    role: "Senior Property Consultant",
    phone: "+971 50 666 7788",
    email: "james@provident.ae",
    languages: ["English"],
    specialties: ["Apartments", "Rentals", "First-time buyers"],
    type: "agent",
    img: "James O'Connor portrait",
    bio: "Apartment and rental specialist known for moving first-time buyers into their first Dubai home.",
  },
];

export const DEVELOPERS: Developer[] = [
  {
    id: 501,
    slug: "emaar-properties",
    name: "Emaar Properties",
    region: "Downtown, Marina, Creek",
    founded: 1997,
    deliveries: 95000,
    img: "Emaar tower skyline",
    description:
      "The developer behind Downtown Dubai, Dubai Marina and Dubai Creek Harbour, with one of the strongest handover records in the region.",
    projects: ["Marina Vista Towers", "Creek Harbour Residences"],
  },
  {
    id: 502,
    slug: "nakheel",
    name: "Nakheel",
    region: "Palm, JVC, Discovery Gardens",
    founded: 2001,
    deliveries: 40000,
    img: "Nakheel palm island",
    description:
      "Master developer of the Palm Jumeirah and Jumeirah Village Circle, delivering signature waterfront and community living.",
    projects: ["Palm Frond Signature Homes", "JVC Garden Terraces"],
  },
  {
    id: 503,
    slug: "damac-properties",
    name: "Damac Properties",
    region: "Business Bay, JVC",
    founded: 2002,
    deliveries: 46000,
    img: "Damac tower facade",
    description:
      "A major private developer blending residential towers, serviced residences and international brand collaborations.",
    projects: ["Business Bay Core"],
  },
  {
    id: 504,
    slug: "al-barari",
    name: "Al Barari",
    region: "Al Barari",
    founded: 2005,
    deliveries: 900,
    img: "Al Barari green estate",
    description:
      "An ultra-luxury botanical community of lakefront villas set within one of the region's most biodiverse estates.",
    projects: ["Al Barari Oasis Estate"],
  },
];

export const SERVICES = [
  {
    slug: "property-buying",
    name: "Property Buying",
    icon: "key",
    blurb: "End-to-end buying support from search to handover, with negotiation and legal coordination.",
    points: ["Property search", "Negotiation", "Legal & conveyancing", "Handover support"],
  },
  {
    slug: "property-selling",
    name: "Property Selling",
    icon: "tag",
    blurb: "Data-backed valuations, targeted marketing and a sales process built around your timeline.",
    points: ["Valuation", "Marketing & staging", "Viewing management", "Closing coordination"],
  },
  {
    slug: "property-renting",
    name: "Property Renting",
    icon: "file",
    blurb: "Tenant sourcing, documentation and management for landlords and corporate tenants.",
    points: ["Tenant sourcing", "Ejari & contracts", "Rent collection", "Renewal management"],
  },
  {
    slug: "property-management",
    name: "Property Management",
    icon: "gear",
    blurb: "Full-service management that protects your asset's value and keeps cash flow predictable.",
    points: ["Tenant liaison", "Maintenance", "Service charge admin", "Monthly reporting"],
  },
  {
    slug: "investment-advisory",
    name: "Investment Advisory",
    icon: "chart",
    blurb: "Yield, capital growth and exit strategy analysis tailored to your portfolio goals.",
    points: ["Market analysis", "Yield modelling", "Portfolio review", "Exit planning"],
  },
  {
    slug: "relocation-services",
    name: "Relocation Services",
    icon: "home",
    blurb: "A single point of contact for corporates and individuals moving to Dubai.",
    points: ["Area selection", "Viewing tours", "Utility setup", "Family settlement"],
  },
];

export const FAQS = [
  {
    q: "How do I book a viewing?",
    a: "Use the 'Book a viewing' form on any property page, or contact us directly by phone or WhatsApp. We usually confirm same-day viewings within 24 hours.",
  },
  {
    q: "What fees do buyers pay in Dubai?",
    a: "Buyers typically pay a 4% DLD transfer fee (with a small fixed portion), plus agency commission of 2% and the registration fee. We itemise every cost before you commit.",
  },
  {
    q: "Can I buy off-plan with a payment plan?",
    a: "Yes. Most 2026 launches run 10% down with the balance split across milestones, and several plans extend past handover. We'll match plans to your cash flow.",
  },
  {
    q: "Do you manage the property after purchase?",
    a: "Yes — our property management team handles leasing, maintenance and reporting for buyers and landlords, with a dedicated manager for each portfolio.",
  },
  {
    q: "Which areas do you cover?",
    a: "We cover the full emirate, with deep specialism in Dubai Marina, Downtown, Palm Jumeirah, Dubai Hills, JVC and Business Bay.",
  },
  {
    q: "How do mortgage pre-approvals work?",
    a: "We partner with all major UAE banks. After a short document review we can secure pre-approval in 3–5 working days, covering up to 80% of the property value.",
  },
];